### ISSUE TITLE
IE8 bug

### ISSUE THREAD

**Issue by jmelnik** [yanickrochon/jquery.uix.multiselect#8] opened 2013-01-09 05:23 UTC
Sorry to find another!

IE may be the bane of my existence, but I'm forced to live with it. I just finished testing on firefox and chrome and everything (with the exception of the refresh bug), works great so far.

IE8 is throwing a 'object doesn't support this property or method' bug on line 894 char 17, here's the loop in question (the error is in the "if" line):

```
for (var i = 0; i < this._elements.length; i++) {
    if (!$.contains(p, this._elements[i].optionElement[0]) ||  _groupsRemoved.indexOf(this._elements[i].optGroup) > -1)) {
        this._elements[i].listElement.remove();
        this._elements.splice(i--, 1);
     }
}
```

I think it has to do with indexOf with IE8, but I haven't figured out a workaround yet to submit a PR.

**Comment by yanickrochon** [comment] 2013-01-09 05:32
Yes, while trying to find a workaround for #7 , I realized that `optGroup` should have been `optionGroup`. Since I use both as function arg and object property, I got it confused there.

Thank you for your tests!

**Comment by jmelnik** [comment] 2013-01-09 14:23
Don't thank me-- thank you for such a great plugin! The performance improvement over the previous version alone is amazing. I should get to test this a little later today-- I'll comment as soon as I get a chance to test it out.

**Comment by jmelnik** [comment] 2013-01-10 14:53
Still getting this error, and there's lots of google fodder on indexOf with IE < v9 -- I'll try to figure out the best workaround and create a PR some time today hopefully. If you have any other ideas or get to it first, just post back.

**Comment by yanickrochon** [comment] 2013-01-10 15:18
[This](http://stackoverflow.com/questions/3629183/why-doesnt-indexof-work-on-an-array-ie8) is how this issue could be resolved.

The widget needs to implement an indexOf if it does not exist. Because I'm not a fan of overriding prototypes, You (or II) will have to add an utility function to properly check if an item exists in the array.

**Comment by jmelnik** [comment] 2013-01-10 15:23
Yep ... I was just looking at that post myself, and I'm not a fan of prototype overrides either but before seeing that post, I found another way to fix it (sent a PR) though I'm not sure I understand why. 

If IE < 9 doesn't understand indexOf it shouldn't  matter whether or not there's an option group but my fix does work on IE8 with or without an option group. weird.

**Comment by jmelnik** [comment] 2013-01-10 15:36
I must be having a brain spasm-- forget that PR. The clear doesn't work then, lol. I'll work on a utility function for checking the index.

**Comment by jmelnik** [comment] 2013-01-10 16:18
I think there's more going on here than just the indexOf bug. When I add an option group and do $.empty() to empty  the underlying select list, the single option group in the widget is still there, and each time I select another option it's being added to the widget again.

**Comment by jmelnik** [comment] 2013-01-10 16:21
I should add that I'm trying to use inArray to replace the indexOf to fix the IE bug, but it's difficult to see if that's working when it doesn't appear to be working with indexOf in the first place. We probably need to track down the option group issue first, then fix the indexOf bug.

**Comment by yanickrochon** [comment] 2013-01-10 16:45
Could you provide a test case to reproduce the error you are describing?

**Comment by jmelnik** [comment] 2013-01-10 19:19
The page I'm working on is pretty complicated but basically I have a simple single value drop down that triggers the .ajax retrieval of the options in JSON. I'm not using an option group, but when troubleshooting this issue I simply wrapped my options in a single option group for testing purposes. Something like this:

```
<select id="myselect">
  <optgroup label="Group1">
    <option value="item1">Item1</option>
    <option value="item2">Item2</option>
    <option value="item3">Item3</option>
  </optgroup>
</select>
```

Then when the drop down changes, I empty the list with $("#myselect").empty(), change to the new options, and refresh the widget with $("#myselect").multiselect('refresh'). I also empty it when the drop down is set to the default "Please Select..." option. 

And each time I do that, the option group is re-added to the select widget:
![screencap](https://f.cloud.github.com/assets/305856/57813/8d27cd66-5b5a-11e2-8a23-7eec64140013.png)

**Comment by jmelnik** [comment] 2013-01-10 19:20
And actually, in this case it seems it might be acceptable to override the prototype rather than create a whole new function. The override is pretty simple and fixed the issue non-compliant browsers:

```
if (!Array.prototype.indexOf) {
    Array.prototype.indexOf = function (obj, start) {
        for (var i = (start || 0), j = this.length; i < j; i++) {
            if (this[i] === obj) { return i; }
        }
        return -1;
    }
}
```

Note that even when this issue is fixed, I still have the replicating option groups issue. I'm still working on trying to track it down. I'm starting to suspect it's ajax related.

**Comment by yanickrochon** [comment] 2013-01-11 03:14
In a moment of total facepalm, I realized that jQuery _does_ have a `$.inArray(elem, arr);` function! Thus replace all array's `ìndexOf` can be quickly and cleanly fixed by using the very library that this widget is baed upon... :)

Also, is this option group bug only related to IE8? Because should we resolve this issue, then create a new one to address the option group problem separatly.

**Comment by jmelnik** [comment] 2013-01-11 15:02
I've had plenty of facepalms myself (that PR request being one). I'm not a jquery export, so I just figured there was a programmatic reason for using indexOf in stead of inArray, lol. .

And no, the option group bug isn't IE8 specific-- firefox has it was well, not sure about chrome I'll test that today. I'll also try to do a PR for the indexOf -> inArray change and then open a new issue for the option group replication if it still exists.

**Comment by yanickrochon** [comment] 2013-01-11 15:09
Excellent! Thank you for your contribution!

**Closed as completed** 2013-01-13 01:37 UTC
Labels: bug
